// flow-typed signature: d88c39455ada5327e3bf7a6aae2c82bb
// flow-typed version: <<STUB>>/chakram_v^1.5.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chakram'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chakram' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chakram/dist/chakram' {
  declare module.exports: any;
}

declare module 'chakram/dist/chakram.min' {
  declare module.exports: any;
}

declare module 'chakram/examples/dweet' {
  declare module.exports: any;
}

declare module 'chakram/examples/randomuser' {
  declare module.exports: any;
}

declare module 'chakram/examples/spotify' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/compression' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/comprise' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/cookie' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/header' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/json' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/responsetime' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/schema' {
  declare module.exports: any;
}

declare module 'chakram/lib/assertions/statuscode' {
  declare module.exports: any;
}

declare module 'chakram/lib/chakram' {
  declare module.exports: any;
}

declare module 'chakram/lib/debug' {
  declare module.exports: any;
}

declare module 'chakram/lib/methods' {
  declare module.exports: any;
}

declare module 'chakram/lib/plugins' {
  declare module.exports: any;
}

declare module 'chakram/lib/utils/objectPath' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/compression' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/cookie' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/header' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/json' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/responsetime' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/schema' {
  declare module.exports: any;
}

declare module 'chakram/test/assertions/statuscode' {
  declare module.exports: any;
}

declare module 'chakram/test/bootstrap' {
  declare module.exports: any;
}

declare module 'chakram/test/core/base' {
  declare module.exports: any;
}

declare module 'chakram/test/core/debug' {
  declare module.exports: any;
}

declare module 'chakram/test/core/documentation-examples' {
  declare module.exports: any;
}

declare module 'chakram/test/core/methods' {
  declare module.exports: any;
}

declare module 'chakram/test/core/plugins' {
  declare module.exports: any;
}

declare module 'chakram/test/core/warnings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chakram/dist/chakram.js' {
  declare module.exports: $Exports<'chakram/dist/chakram'>;
}
declare module 'chakram/dist/chakram.min.js' {
  declare module.exports: $Exports<'chakram/dist/chakram.min'>;
}
declare module 'chakram/examples/dweet.js' {
  declare module.exports: $Exports<'chakram/examples/dweet'>;
}
declare module 'chakram/examples/randomuser.js' {
  declare module.exports: $Exports<'chakram/examples/randomuser'>;
}
declare module 'chakram/examples/spotify.js' {
  declare module.exports: $Exports<'chakram/examples/spotify'>;
}
declare module 'chakram/lib/assertions/compression.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/compression'>;
}
declare module 'chakram/lib/assertions/comprise.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/comprise'>;
}
declare module 'chakram/lib/assertions/cookie.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/cookie'>;
}
declare module 'chakram/lib/assertions/header.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/header'>;
}
declare module 'chakram/lib/assertions/index' {
  declare module.exports: $Exports<'chakram/lib/assertions'>;
}
declare module 'chakram/lib/assertions/index.js' {
  declare module.exports: $Exports<'chakram/lib/assertions'>;
}
declare module 'chakram/lib/assertions/json.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/json'>;
}
declare module 'chakram/lib/assertions/responsetime.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/responsetime'>;
}
declare module 'chakram/lib/assertions/schema.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/schema'>;
}
declare module 'chakram/lib/assertions/statuscode.js' {
  declare module.exports: $Exports<'chakram/lib/assertions/statuscode'>;
}
declare module 'chakram/lib/chakram.js' {
  declare module.exports: $Exports<'chakram/lib/chakram'>;
}
declare module 'chakram/lib/debug.js' {
  declare module.exports: $Exports<'chakram/lib/debug'>;
}
declare module 'chakram/lib/methods.js' {
  declare module.exports: $Exports<'chakram/lib/methods'>;
}
declare module 'chakram/lib/plugins.js' {
  declare module.exports: $Exports<'chakram/lib/plugins'>;
}
declare module 'chakram/lib/utils/objectPath.js' {
  declare module.exports: $Exports<'chakram/lib/utils/objectPath'>;
}
declare module 'chakram/test/assertions/compression.js' {
  declare module.exports: $Exports<'chakram/test/assertions/compression'>;
}
declare module 'chakram/test/assertions/cookie.js' {
  declare module.exports: $Exports<'chakram/test/assertions/cookie'>;
}
declare module 'chakram/test/assertions/header.js' {
  declare module.exports: $Exports<'chakram/test/assertions/header'>;
}
declare module 'chakram/test/assertions/json.js' {
  declare module.exports: $Exports<'chakram/test/assertions/json'>;
}
declare module 'chakram/test/assertions/responsetime.js' {
  declare module.exports: $Exports<'chakram/test/assertions/responsetime'>;
}
declare module 'chakram/test/assertions/schema.js' {
  declare module.exports: $Exports<'chakram/test/assertions/schema'>;
}
declare module 'chakram/test/assertions/statuscode.js' {
  declare module.exports: $Exports<'chakram/test/assertions/statuscode'>;
}
declare module 'chakram/test/bootstrap.js' {
  declare module.exports: $Exports<'chakram/test/bootstrap'>;
}
declare module 'chakram/test/core/base.js' {
  declare module.exports: $Exports<'chakram/test/core/base'>;
}
declare module 'chakram/test/core/debug.js' {
  declare module.exports: $Exports<'chakram/test/core/debug'>;
}
declare module 'chakram/test/core/documentation-examples.js' {
  declare module.exports: $Exports<'chakram/test/core/documentation-examples'>;
}
declare module 'chakram/test/core/methods.js' {
  declare module.exports: $Exports<'chakram/test/core/methods'>;
}
declare module 'chakram/test/core/plugins.js' {
  declare module.exports: $Exports<'chakram/test/core/plugins'>;
}
declare module 'chakram/test/core/warnings.js' {
  declare module.exports: $Exports<'chakram/test/core/warnings'>;
}
