// flow-typed signature: 9e6d40601a0ed28584ba8a439752bbe4
// flow-typed version: <<STUB>>/tcp-port-used_v^1.0.1/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tcp-port-used'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tcp-port-used' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tcp-port-used/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tcp-port-used/index' {
  declare module.exports: $Exports<'tcp-port-used'>;
}
declare module 'tcp-port-used/index.js' {
  declare module.exports: $Exports<'tcp-port-used'>;
}
declare module 'tcp-port-used/test.js' {
  declare module.exports: $Exports<'tcp-port-used/test'>;
}
